services:

# ── FRONTEND ────────────────────────────────────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_WS_URL: "ws://localhost:8000/ws"
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
      BACKEND_INTERNAL_URL: "http://backend:8000"
      # ── Hot-reload fix ──────────────────────────
      TURBOPACK_WATCH_POLL: "200" # fuerza a turbopack a usar polling, aunque al final usamos webpack, por las dudas
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "200"
    volumes:
      - ./frontend:/app  # hot-reload - react-scripts reinicia cuando detecta un guardado con cambios
      - /app/node_modules # evita que el volumen sobreescriba node_modules con el del host, que rompería el hot-reload
    depends_on:
      - backend

# ── BACKEND ────────────────────────────────────────────────────────────────

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
        - ./backend:/app  # hot-reload - uvicorn reinicia cuando detecta un guardado con cambios

    command: >
      uvicorn app.main:app
        --host 0.0.0.0
        --port 8000
        --reload
        --reload-dir /app/app

# ── SIMULADOR DEL PI ────────────────────────────────────────────────────────────

  pi_mock:
    build:
      context: ./pi_mock
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./pi_mock:/app
      - ./secrets:/run/secrets:ro        # certificados read-only

# ── REDIS ──────────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  redis_data: