import { cookies } from "next/headers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Button from "@/components/Button";
import { logout } from "@/lib/api/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const token = (await cookies()).get("session_token")?.value;


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {token && (
          <nav className="w-full h-16 flex items-center justify-end gap-4 px-6 bg-secondary-dark">
            <Button onClick={logout}>
              Log out
            </Button>
          </nav>
        )}
        {children}
      </body>
    </html>
  );
}
